### PR TITLE
Fix a typo in method name and switch from process.cwd() to __dirname

### PR DESCRIPTION
**Pull request by ya-sach1**
I realized halfway that switching to __dirname is not exactly beneficial to this project, as it's probably never gonna become a monorepo or switch it's build directory, but I feel like it's an improvement nonetheless. I wouldn't be surprised if the PR doesn't get accepted, lol.

### CODE REVIEW

**Comment by melike2d** [comment]
yeah it wont get merged #rekt #destroyed #yousuck

**Comment by ya-sach1** [comment]
You're so rude :(((

**Comment by melike2d** [comment]
im kiddinngggg

**Comment by melike2d** [comment]
thanks for the pr!

**Review by melike2d — APPROVED** [review]
less goooo

**Pull request merged**
